### ISSUE TITLE
is open dance playable now?

### ISSUE THREAD

**Issue by Quenii** [WodsonKun/OpenDance#1]
is open dance playable now?
and do you have plan to support kinect?

**Comment by WodsonKun** [comment]
Hi! How're you doing?
Currently no, it's not playable yet, there's a lot of stuff to add and fix at this point....
About the Kinect support, I can't guarantee it, as I have to learn how .gesture files work and how to make them work with the Kinect extension for GMS2.3

Also, I don't have a Kinect for testing and debugging lmao
AND... To implement Kinect support, I would have to add UbiArt timing support (at this moment, we only have BlueStar timing support)

**Comment by Quenii** [comment]
without kinect, then how would you like to match dancer's pose or movement?

**Comment by Quenii** [comment]
in open-dance.yyp, i saw lots of file like this:
"filePath":"datafiles/ComeBackHome/pictos","resourceVersion":"1.0","name":"home_sh.png"
but didn't find them in project
so, how to get them

**Comment by WodsonKun** [comment]
> in open-dance.yyp, i saw lots of file like this: "filePath":"datafiles/ComeBackHome/pictos","resourceVersion":"1.0","name":"home_sh.png" but didn't find them in project so, how to get them

Those files aren't included for copyright issues, they're song files
